pub struct Filter {
    search_text: String,
    languages: Option<Vec<Language>>,
}

pub enum Language {
    Abkhazian,
    Afrikaans,
    Albanian,
    Amharic,
    Arabic,
    Aragonese,
    Armenian,
    Assamese,
    Asturian,
    Azerbaijani,
    Basque,
    Belarusian,
    Bengali,
    Bosnian,
    Breton,
    Bulgarian,
    Burmese,
    Catalan,
    ChineseCantonese,
    ChineseSimplified,
    ChineseTraditional,
    ChineseBilingual,
    Croatian,
    Czech,
    Danish,
    Dari,
    Dutch,
    English,
    Esperanto,
    Estonian,
    Extremaduran,
    Finnish,
    French,
    Gaelic,
    Galician,
    Georgian,
    German,
    Greek,
    Hebrew,
    Hindi,
    Hungarian,
    Icelandic,
    Igbo,
    Indonesian,
    Interlingua,
    Irish,
    Italian,
    Japanese,
    Kannada,
    Kazakh,
    Khmer,
    Korean,
    Kurdish,
    Kyrgyz,
    Latvian,
    Lithuanian,
    Luxembourgish,
    Macedonian,
    Malay,
    Malayalam,
    Manipuri,
    Marathi,
    Mongolian,
    Montenegrin,
    Navajo,
    Nepali,
    NorthernSami,
    Norwegian,
    Occitan,
    Odia,
    Persian,
    Polish,
    Portuguese,
    PortugueseBr,
    PortugueseMz,
    Pushto,
    Romanian,
    Russian,
    Santali,
    Serbian,
    Sindhi,
    Sinhalese,
    Slovak,
    Slovenian,
    Somali,
    SorbianLanguages,
    SouthAzerbaijani,
    Spanish,
    SpanishEU,
    SpanishLA,
    Swahili,
    Swedish,
    Syriac,
    Tagalog,
    Tamil,
    Tatar,
    Telugu,
    Tetum,
    Thai,
    TokiPona,
    Turkish,
    Turkmen,
    Ukrainian,
    Urdu,
    Uzbek,
    Vietnamese,
    Welsch,
}

impl From<Language> for &str {
    fn from(value: Language) -> Self {
        match value {
            Language::Abkhazian => "abk",
            Language::Afrikaans => "afr",
            Language::Albanian => "alb",
            Language::Amharic => "Amh",
            Language::Arabic => "ara",
            Language::Aragonese => "arg",
            Language::Armenian => "arm",
            Language::Assamese => "asm",
            Language::Asturian => "ast",
            Language::Azerbaijani => "aze",
            Language::Basque => "Basque",
            Language::Belarusian => "Belarusian",
            Language::Bengali => "Bengali",
            Language::Bosnian => "Bosnian",
            Language::Breton => "Breton",
            Language::Bulgarian => "Bulgarian",
            Language::Burmese => "Burmese",
            Language::Catalan => "Catalan",
            Language::ChineseCantonese => "ChineseCantonese",
            Language::ChineseSimplified => "ChineseSimplified",
            Language::ChineseTraditional => "ChineseTraditional",
            Language::ChineseBilingual => "ChineseBilingual",
            Language::Croatian => "Croatian",
            Language::Czech => "Czech",
            Language::Danish => "Danish",
            Language::Dari => "Dari",
            Language::Dutch => "Dutch",
            Language::English => "English",
            Language::Esperanto => "Esperanto",
            Language::Estonian => "Estonian",
            Language::Extremaduran => "Extremaduran",
            Language::Finnish => "Finnish",
            Language::French => "French",
            Language::Gaelic => "Gaelic",
            Language::Galician => "Galician",
            Language::Georgian => "Georgian",
            Language::German => "German",
            Language::Greek => "Greek",
            Language::Hebrew => "Hebrew",
            Language::Hindi => "Hindi",
            Language::Hungarian => "Hungarian",
            Language::Icelandic => "Icelandic",
            Language::Igbo => "Igbo",
            Language::Indonesian => "Indonesian",
            Language::Interlingua => "Interlingua",
            Language::Irish => "Irish",
            Language::Italian => "Italian",
            Language::Japanese => "Japanese",
            Language::Kannada => "Kannada",
            Language::Kazakh => "Kazakh",
            Language::Khmer => "Khmer",
            Language::Korean => "Korean",
            Language::Kurdish => "Kurdish",
            Language::Kyrgyz => "Kyrgyz",
            Language::Latvian => "Latvian",
            Language::Lithuanian => "Lithuanian",
            Language::Luxembourgish => "Luxembourgish",
            Language::Macedonian => "Macedonian",
            Language::Malay => "Malay",
            Language::Malayalam => "Malayalam",
            Language::Manipuri => "Manipuri",
            Language::Marathi => "Marathi",
            Language::Mongolian => "Mongolian",
            Language::Montenegrin => "Montenegrin",
            Language::Navajo => "Navajo",
            Language::Nepali => "Nepali",
            Language::NorthernSami => "NorthernSami",
            Language::Norwegian => "Norwegian",
            Language::Occitan => "Occitan",
            Language::Odia => "Odia",
            Language::Persian => "Persian",
            Language::Polish => "Polish",
            Language::Portuguese => "Portuguese",
            Language::PortugueseBr => "PortugueseBr",
            Language::PortugueseMz => "PortugueseMz",
            Language::Pushto => "Pushto",
            Language::Romanian => "Romanian",
            Language::Russian => "Russian",
            Language::Santali => "Santali",
            Language::Serbian => "Serbian",
            Language::Sindhi => "Sindhi",
            Language::Sinhalese => "Sinhalese",
            Language::Slovak => "Slovak",
            Language::Slovenian => "Slovenian",
            Language::Somali => "Somali",
            Language::SorbianLanguages => "SorbianLanguages",
            Language::SouthAzerbaijani => "SouthAzerbaijani",
            Language::Spanish => "Spanish",
            Language::SpanishEU => "SpanishEU",
            Language::SpanishLA => "SpanishLA",
            Language::Swahili => "Swahili",
            Language::Swedish => "Swedish",
            Language::Syriac => "Syriac",
            Language::Tagalog => "Tagalog",
            Language::Tamil => "Tamil",
            Language::Tatar => "Tatar",
            Language::Telugu => "Telugu",
            Language::Tetum => "Tetum",
            Language::Thai => "Thai",
            Language::TokiPona => "TokiPona",
            Language::Turkish => "Turkish",
            Language::Turkmen => "Turkmen",
            Language::Ukrainian => "Ukrainian",
            Language::Urdu => "Urdu",
            Language::Uzbek => "Uzbek",
            Language::Vietnamese => "Vietnamese",
            Language::Welsch => "Welsch",
        }
    }
}
